### ISSUE TITLE
curl: not found

### ISSUE THREAD

**Issue by 9Mad-Max5** [nichobi/sponsorblockcast#11]
The following messages appears in the Dockerlog:

/usr/bin/sponsorblockcast: line 19: curl: not found

**Comment by nichobi** [comment]
Sorry for the slow response, the Docker stuff was contributed and I'm not overly familiar with how it works. Hopefully that fixes it, but do let me know if not!

**Comment by 9Mad-Max5** [comment]
Seems to work now
