### ISSUE TITLE
Casting to ShieldTV - no difference with/without Sponsorblockcast

### ISSUE THREAD

**Issue by zilexa** [nichobi/sponsorblockcast#15]
I use docker compose, network_mode=host. 
The ShieldTV and the server running docker are both via LAN wired connected, each to a small switch and both switches are connected to the router. There is no ISP modem/router involved (the router has an SFP module, fiber internet).

I would expects prerolls and midrolls ads to be blocked, but they aren't. Log only shows:

```
watching 832a57877691d6e11a53f8f73f61ac9f, pid=24
watching 832a57877691d6e11a53f8f73f61ac9f, pid=25
```
The second line appeared after restarting the container, which I did after casting a few videos and seeing ads.

**Comment by zilexa** [comment]
So sorry, I didn't understand from the readme how Sponsorblock is able to identify ads and block them. I understand now it is based on the community, users submitting IDs of sponsored videos. It might make sense in that case that I still see ads. 

Is there a way to track if something has been identified and blocked?

Also, is there a difference between sponsorblockcast and https://github.com/erdnaxeli/castblock in terms of functionality?
I see there is a debug logging option and muting native ads.

**Comment by ajayyy** [comment]
This skips sponsorships inside videos, not pre-rolls added by YouTube.

Examples: https://sb.ltn.fi/?category=sponsor&sort=-votes

**Comment by zilexa** [comment]
Thanks for clarifying!

**Comment by joszz** [comment]
Seems to me that ShieldTV is not providing the URL or videoId when go-chromecast status is executed, see this issue;
https://github.com/nichobi/sponsorblockcast/issues/16

This will never work for that reason. I own a 2017 model with latest firmware
