### ISSUE TITLE
jq: error

### ISSUE THREAD

**Issue by unbraind** [nichobi/sponsorblockcast#2]
I get the following error when a chromcast starts playing:
> jq: error (at <stdin>:0): string ("") and number (11.649165) cannot be added

**Comment by nichobi** [comment]
Interesting, I haven't run into this myself, maybe depends on the jq version. Can you try making the following substitution on line 20 in `sponsorblockcast.sh`
```diff
get_segments () {
   if [ ! -f "$id".segments ]
   then
     curl -fs "https://sponsor.ajay.app/api/skipSegments?videoID=$id&categories=$categories" |\
-    jq -r '.[] | (.segment|join(" ")) + " " + .category' > "$id.segments"
+    jq -r '.[] | (.segment|map_values(tostring)|join(" ")) + " " + .category' > "$id.segments"
   fi
 }
```
Hopefully that's enough to fix it, if not I'll have to look into it further tomorrow.

**Comment by unbraind** [comment]
Thank you very much, now it works!
