### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by maivorbim** [nichobi/sponsorblockcast#3]
Hello, thank you for all the work and for a great alternative to the castblock script. Is there any chance you could make a Docker image for your script, for easy installation on Home Assistant ? Similar to this: https://hub.docker.com/r/stephen304/castblock/dockerfile

Also see the following topic: https://community.home-assistant.io/t/castblock-sponsorblock-for-chromecasted-videos/224847

https://developers.home-assistant.io/docs/add-ons

Thanks

**Comment by nichobi** [comment]
Thanks for the kind words!

I don't use Docker myself, so not entirely familiar with how to create docker images. It probably wouldn't be too hard to adapt the Castblock file, but it would be hard for me to test that everything works right. I might give it a go at some point, but for now I'm working on a rewrite with much improved performance.

If you or anyone else wants to make one, I'd be happy to help in any way I can and include a link to it in the installation instructions!

**Comment by KayOhtie** [comment]
Submitted #8 for including a Dockerfile and example docker-compose.yaml. I'd accept the other fix first, I accidentally created my branch for the Dockerfile with the fixes too, oops.

**Comment by nichobi** [comment]
Closed by merging #8
